---
- name: Add Jenkins repository
  yum_repository:
    name: jenkins
    description: Jenkins Repo
    baseurl: http://pkg.jenkins.io/redhat-stable/
    gpgcheck: yes
    repo_gpgcheck: no
    gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    enabled: yes

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Enable and start Jenkins
  systemd:
    name: jenkins
    enabled: yes
    state: started

- name: Add Jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes
