apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/zmramadan12/Graduation-Project.git'
    targetRevision: HEAD
    path: k8s

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ivolve

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
